name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  system-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo build
    - env:
        DATABASE.URL: postgres://postgres:postgres@localhost:5432/postgres
        SERVER_PORT: 8081
        RUST_LOG: debug
      timeout-minutes: 5
      run: target/debug/github-system-tests &> system-tests/application.log &
    - working-directory: system-tests
      run: newman run github-system-tests.postman_collection.json -e system-test.postman_environment.json
    - uses: actions/upload-artifact@v3
      with:
        name: system-tests-log
        path: system-tests/application.log