name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  system-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cargo build
    - env:
        SERVER_PORT: 8081
      run: target/debug/github-system-tests &> /dev/null &
    - run: cd system-tests && newman run github-system-tests.postman_collection.json -e system-test.postman_environment.json