name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  system-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo build
    - run: docker run --rm -d --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:11-alpine
    - run: sleep 30
    - run: docker logs postgres
    - env:
        DATABASE.URL: postgres://postgres:postgres@localhost:5432/postgres
        SERVER_PORT: 8081
        RUST_LOG: debug
      timeout-minutes: 5
      run: target/debug/github-system-tests &> ./system-test.log &
    - working-directory: system-tests
      run: newman run github-system-tests.postman_collection.json -e system-test.postman_environment.json
    - run: cat system-test.log